substitutions:
  device_name: "myesp32garden"
#  api_key: !secret api_385e88_key 

packages:

  boot:    !include packages/on_boot.yaml
  globals: !include packages/globals.yaml

  drv8833: !include packages/vanne/drv8833.yaml
  api_key: !include packages/secrets/esp_385e88.yaml

  network: 
    !include  
    file: packages/network.yaml
    vars:
      network_ip: "192.168.1.44"

  deep_sleep:
    !include  
    file: packages/deep_sleep.yaml
    vars:
#      deep_sleep_id: deep_sleep_ctrl
#      deep_sleep_pin: GPIO33
      deep_sleep_status_pin: GPIO3    

  latch1: 
    !include  
    file: packages/sensors/button_latch.yaml
    vars:
      sensor_name: "Maintenance button"
      switch_pin: GPIO4

  ui:    !include packages/irrigation_ui.yaml
  vanne1: 
    !include  
    file: packages/vanne/parameters.yaml
    vars:
      vanne_id: 0
      vanne_pin_a: GPIO12
      vanne_pin_b: GPIO13
  vanne2:
    !include   
    file: packages/vanne/parameters.yaml
    vars:
      vanne_id: 1
      vanne_pin_a: GPIO16
      vanne_pin_b: GPIO17
  vanne3: 
    !include  
    file: packages/vanne/parameters.yaml
    vars:
      vanne_id: 2
      vanne_pin_a: GPIO18
      vanne_pin_b: GPIO19
  vanne4: 
    !include
    file: packages/vanne/parameters.yaml
    vars:
      vanne_id: 3
      vanne_pin_a: GPIO25
      vanne_pin_b: GPIO26


  scheduler: !include packages/scheduler.yaml
