# --------------------
# Vanne paremeter
# ce package est appelé pour chaque Vanne pour initialiser ${vanne_id}
# -------------------
globals:
    
  - id: vanne${vanne_id}_volume
    type: float
    restore_value: yes
    initial_value: "0"

  - id: vanne${vanne_id}_cycles
    type: uint32_t
    restore_value: yes
    initial_value: "0"

  - id: vanne${vanne_id}_state
    type: bool
    restore_value: true
    initial_value: 'false'

    
switch:
 
  - platform: template
    name: "🚰 Vanne ${vanne_id}"
    id: sw_vanne${vanne_id}
    optimistic: false

    lambda: |-
      return id(vanne_state)[${vanne_id}];

    turn_on_action:
      - lambda: |-
          //if (id(fsm_lock) && id(machine_state) != ST_MANUAL_TIMEOUT)   return;      
          id(vanne_active) = ${vanne_id};
          ESP_LOGI("UI", "MANUAL OPEN vanne%d",${vanne_id});
          id(machine_state) = ST_MANUAL_OPEN;


    turn_off_action:
      - lambda: |-
          //if (id(fsm_lock))   return;
          id(vanne_active) = ${vanne_id};
          id(machine_state) = ST_MANUAL_CLOSE;
          ESP_LOGI("UI", "MANUAL CLOSE vanne%d", ${vanne_id});

      
select:
  - platform: template
    name: "🎯 Vanne${vanne_id} Preset irrigation"
    id: vanne${vanne_id}_preset

    options:
      - "Off"
      - "Tous les jours"
      - "Lun-Mer-Ven-Dim"
      - "Week-end"

    lambda: |-
      if (id(vanne_day)[${vanne_id}] == 0)
        return std::string("Off");

      if (id(vanne_day)[${vanne_id}] == (DAY_LUNDI | DAY_MARDI| DAY_MERCREDI | DAY_JEUDI | DAY_VENDREDI | DAY_SAMEDI | DAY_DIMANCHE))
        return std::string("Tous les jours");

      if (id(vanne_day)[${vanne_id}] == (DAY_LUNDI | DAY_MERCREDI | DAY_VENDREDI | DAY_DIMANCHE))
        return std::string("Lun-Mer-Ven-Dim");

      if (id(vanne_day)[${vanne_id}] == (DAY_SAMEDI | DAY_DIMANCHE))
        return std::string("Week-end");

      return std::string("Off");

    set_action:
      - lambda: |-
          if (x == "Off")
            id(vanne_day)[${vanne_id}] = 0;

          else if (x == "Tous les jours")
            id(vanne_day)[${vanne_id}] = DAY_LUNDI | DAY_MARDI| DAY_MERCREDI | DAY_JEUDI | DAY_VENDREDI | DAY_SAMEDI | DAY_DIMANCHE;

          else if (x == "Lun-Mer-Ven-Dim")
            id(vanne_day)[${vanne_id}] =
              DAY_LUNDI | DAY_MERCREDI | DAY_VENDREDI | DAY_DIMANCHE;

          else if (x == "Week-end")
            id(vanne_day)[${vanne_id}] =
              DAY_SAMEDI | DAY_DIMANCHE;

