sensor:

  - platform: adc
    pin: ${sensor_pin}

    name: "${sensor_name}"

    id: ${sensor_id}

    attenuation: 12db

    update_interval: 60s

    filters:
      - calibrate_linear:
          - 2.7 -> 0
          - 1.3 -> 100

      - clamp:
          min_value: 0
          max_value: 100

    unit_of_measurement: "%"